### ISSUE TITLE
Package Modaliases flaky

### ISSUE THREAD

**Issue by cskau** [canonical/nvidia-graphics-drivers#13]
The Ubuntu nvidia packages appear to have a rather arbitrary list of supported (hardware) aliases.
I've extracted the aliases listed in the packages nvidia-{304,340,384} here:
https://gist.github.com/cskau/238e6497e030e1d8569c25a66f7e885e

For instance only `nvidia-340` lists any of the `pci:v000010DEd00001140sv*` devices.
Meanwhile, the kernel module itself claims a much broader support:
```
~> modinfo /lib/modules/4.10.0-37-generic/updates/dkms/nvidia_384.ko
...
alias:          pci:v000010DEd00000E00sv*sd*bc04sc80i00*
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
```
Which I believe is also corroborated by the `pci_device_id` table in `nv.c`.
As well as anecdotal evidence in that I'm running on `nvidia_384.ko` right now.

From poking around a bit I'm guessing the alias list is generated by `nvidia_supported`, which tries to extract the list from a README and grep'ing through `nv-kernel.o`.
To be frank I think all the options here have their own draw-backs, but perhaps relying on the module's   `pci_device_id` table would be more robust? (Whether that's extracted from `nv.c` or interrogating the compiled module)

Background/motivation:
`ubuntu-drivers` / 'Additional Drivers' and anyone else relying on the package `Modalias` to match packages to hardware are affected by this.

**Comment by tseliot** [comment]
The IDs that are mentioned in the README file are the ones that are officially supported. Grepping through the nv-kernel.o file hasn't worked in a while. I'm not sure extracting the aliases from a built module would be an option.
